### ISSUE TITLE
menu ziet er raar uit op mobiel

### ISSUE THREAD

**Issue by tibovanheule** [HomeAstrid/website#12]
https://astrid.tibovanheule.space/

![afbeelding](https://user-images.githubusercontent.com/28403026/168444751-540b28ce-5466-476c-b1db-b096d630eaf9.png)

**Comment by RobbeAdriaens-TomTom** [comment]
Should be fixed with the latest commit

**Comment by tibovanheule** [comment]
The commit indeed fixes the issue and is pulled to the online version.
