### ISSUE TITLE
nav ziet er niet uit (ook tablet)

### ISSUE THREAD

**Issue by tibovanheule** [HomeAstrid/website#14]
![afbeelding](https://user-images.githubusercontent.com/28403026/195653543-c948adf5-d48c-4a53-8911-5acf62ab97f4.png)

**Comment by RobbeAdriaens-TomTom** [comment]
The last commit alters the view on phones and tablets to have the different tabs next to each other instead of below each other.

**Comment by tibovanheule** [comment]
Perfect! The last commit indeed solves the problem!

Closing this issue
